commited

diff --git a/web_server/1-install_nginx_web_server b/web_server/1-install_nginx_web_server
--- a/web_server/1-install_nginx_web_server
+++ b/web_server/1-install_nginx_web_server
@@ -2,12 +2,21 @@
 # Installs Nginx with the following configurations:
 #+    Listens on port 80.
 #+    Returns a page containing "Holberton School" when queried
-#++    at the root with a curl GET request.
+#++    at the root with a curl GET request
 
 sudo apt-get update
+
+# Install Nginx
 sudo apt-get install -y nginx
 
-mkdir /var/www/html
-touch /var/www/html/index.html
-echo "Holberton School" > /var/www/html/index.html
-sudo service ngix start
+# Verify if Nginx is installed successfully
+if [ "$(dpkg-query -W -f='${Status}' nginx 2>/dev/null | grep -c "ok installed")" -eq 0 ]; then
+    echo "Installation failed. Exiting."
+    exit 1
+fi
+
+# Configure Nginx to listen on port 80
+sudo sed -i 's/\(listen 80;\)/\1 default_server;/' /etc/nginx/sites-available/default
+
+# Restart Nginx without using systemctl
+sudo service nginx restart
